### ISSUE TITLE
Update gitignore to ignore PyCharm files

### ISSUE THREAD

**Issue by epoulton** [epoulton/tictactoe_ai#1]
I don't think the PyCharm .idea files need to be included in the repo.

**Comment by smriti1313** [comment]
Hi, I did remove the .idea folder from your repo. I gave a PR.

**Comment by epoulton** [comment]
Right on, thank you :-)

**Comment by smriti1313** [comment]
since I am a newbie in this open source contribution thing,thank you for giving me a chance :)
